### ISSUE TITLE
OSX sandbox

### ISSUE THREAD

**Issue by seantree** [Tencent/HaboMalHunter#10]
Hello Guys,

Can you please tell me how to setup the osx sandbox for mac malware samples.
.
It would be very grateful for us, waiting for positive reply.
.
Thanks & Regards
Seantree

**Comment by jingleyang** [comment]
hi,
Do you meaning MacOS?
1. setup an virtual environment of MacOS. For example, VirtualBox.
2. Then find some analysis tools for MacOS programs.
3. Then link them together and collect all the output from the previous tools.
4. Finally, you got your own MacOS sandbox.
Thanks
