### ISSUE TITLE
maybe wrong output from habo.qq.com

### ISSUE THREAD

**Issue by thinkycx** [Tencent/HaboMalHunter#13]
![image](https://user-images.githubusercontent.com/13138128/44733368-09665180-ab1a-11e8-9002-503a48d314bf.png)

The result is from https://habo.qq.com/
and the ELF source code is in the picture.
Why the habo has "文件行为"？

**Comment by jingleyang** [comment]
hi,
文件行为的判定标准是syscall open(), 系统在load ELF文件的时候，会加载so文件，这些都是通过open系统调用打开句柄，然后加载到内存的，所以有文件行为。
Because showing File IO behaviors is linked with syscall open(). When a ELF file is loaded, many defaults so files will be mapped into memory by calling open().
Thanks

**Comment by thinkycx** [comment]
Thanks.
