### ISSUE TITLE
how can i use in vmware

### ISSUE THREAD

**Issue by blackorbird** [Tencent/HaboMalHunter#6]
i look it like lemon sandbox

**Comment by jingleyang** [comment]
hi @shiyelin ,

I consider that VMware is just another kind of Virtual Machine environment. You could try util/update_image/update_image.sh firstly, and than try to follow the instructions of the README.md.

If you got further issues, you are welcome to share it or try to create a pull requests to fix it.

Cheers,
Jingyu
