### ISSUE TITLE
Encounter issue with execution of HaboMalHunter

### ISSUE THREAD

**Issue by webtoo** [Tencent/HaboMalHunter#7]
Following the steps of the readme, when i execute the AnalyzeControl.py, i encounter the following error. Kindly assist.

python AnalyzeControl.py -e ./config.ini -v -l ./test/bin/read.64.elf
Traceback (most recent call last):
  File "AnalyzeControl.py", line 57, in <module>
    import static
ImportError: No module named static

**Comment by jingleyang** [comment]
hi,
If you can try python debug mode (python -m pdb), you may found why static module can not be found.
Thanks
